### ISSUE TITLE
./nodectl --help - Throws a deprecation warning but does nothing else.

### ISSUE THREAD

**Issue by hqakhtar** [pgEdge/cli#129]
**Issue details:**
`./nodectl --help` throws the following warning but does not print help information.
`⚠ 'nc', 'nodectl', & 'ctl' commands deprecated in favor of 'pgedge'`

However, nodectl responds to the other specific commands like:
`./nodectl install pgedge -U superuser-name -P superuser-password -d database-name`

**Expected behaviour:**
Help information should also be printed by nodectl along with the warning.

**Comment by luss** [comment]
This was fixed...
