### ISSUE TITLE
pgedge help synopsis is confusing.

### ISSUE THREAD

**Issue by hqakhtar** [pgEdge/cli#130]
**Issue details:**
`./pgedge --help` displays the help information. However, the argument sequence expected does not seem correct. It shows that the module must follow the command, neither of which are optional:
`./pgedge <module> <command> [parameters] [options]`

Whereas, it accepts the following command without the module name:
`/pgedge install pgedge ...`

**Expected behavior:**
The **SYNOPSIS** should be updated to match the sequence of arguments accepted by pgedge command, or the synopsis should also specify that the default module is "um", or enforce that module is specified.

**Comment by luss** [comment]
planned in backlog
