### ISSUE TITLE
[LOLOR] pgdump not working

### ISSUE THREAD

**Issue by asifnaeem** [pgEdge/cli#142]
There are 2 issues observed while taking dump of the database i.e.

- pgdump fail with error if there is any existing native large object present in the database
- pgdump don't stores LOLOR large objects created in the database

The following command was used to take the dump i.e.
pg_dump -d lolor_db -h HostIP 

PS: -b option is default

**Comment by luss** [comment]
it's working in lolor 1.2.  In any event, further comment on lolor specific stuff belong in github.com/pgedge/lolor
